# Generated by Django 4.2 on 2023-05-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karaoke',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='매장 명')),
                ('remainingSeat', models.IntegerField(blank=True, null=True, verbose_name='잔여석')),
                ('totalSeat', models.IntegerField(blank=True, null=True, verbose_name='총 좌석')),
                ('callNumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='매장 번호')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='매장 주소')),
                ('star', models.FloatField(blank=True, null=True, verbose_name='별점')),
                ('review', models.TextField(blank=True, null=True, verbose_name='매장 후기')),
                ('waiting', models.IntegerField(blank=True, null=True, verbose_name='대기 팀 숫자')),
            ],
            options={
                'verbose_name': '노래방',
                'verbose_name_plural': '노래방',
            },
        ),
    ]
