# Generated by Django 4.2 on 2023-06-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaoke',
            name='image',
            field=models.ImageField(default=None, upload_to='노래방 사진들'),
            preserve_default=False,
        ),
    ]
