# Generated by Django 4.2 on 2023-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0003_remove_karaoke_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaoke',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='karaoke',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
    ]
