# Generated by Django 4.2 on 2023-05-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0004_karaoke_latitude_karaoke_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karaoke',
            name='callNumber',
        ),
        migrations.RemoveField(
            model_name='karaoke',
            name='star',
        ),
        migrations.RemoveField(
            model_name='karaoke',
            name='waiting',
        ),
    ]
