# Generated by Django 4.2 on 2023-05-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0005_remove_karaoke_callnumber_remove_karaoke_star_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaoke',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='매장 명'),
        ),
    ]
