# Generated by Django 4.2 on 2023-05-24 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='앨범 이름')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='앨범 생성일자')),
                ('numOfSongs', models.IntegerField(blank=True, null=True, verbose_name='앨범 수록곡 수')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='앨범 설명')),
                ('member', models.ForeignKey(db_column='member', on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL, verbose_name='사용자 id값')),
            ],
            options={
                'verbose_name': '앨범',
                'verbose_name_plural': '앨범',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='음악 이름')),
                ('singer', models.CharField(blank=True, max_length=40, null=True, verbose_name='가수 이름')),
                ('album', models.ForeignKey(db_column='album', on_delete=django.db.models.deletion.CASCADE, related_name='music', to='albums.album', verbose_name='앨범 id')),
            ],
            options={
                'verbose_name': '음악',
                'verbose_name_plural': '음악',
            },
        ),
    ]
