# Generated by Django 4.2 on 2023-05-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
