# Generated by Django 4.2 on 2023-05-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
    ]
