# Generated by Django 4.2 on 2023-05-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_member_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='점주 여부'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='관리자 페이지 접근 권한'),
        ),
    ]
