# Generated by Django 4.2 on 2023-05-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_member_is_master_alter_member_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_master',
            field=models.IntegerField(default=0, verbose_name='점주 여부'),
        ),
    ]
